import Footer from "./components/footer/Footer";
import Nav from "./components/nav/Nav";
import "./styles/index.scss";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body>
				<Nav />
				<a href="#main-content" className="skip-nav">
					Skip to main content
				</a>
				{children}
				<Footer />
			</body>
		</html>
	);
}
